// Generated by tools/gen_legal_docs.py - do not edit by hand.
// Edit the text in that script and run it again: the app and the pages in the
// repository then always show the same words.

/// The date both pages were last changed.
const String kLegalUpdated = '8 October 2026';

const List<(String, String)> kPrivacySections = [
      (
        'The short version',
        'We keep what the app needs to work: your account, what you post, and who you talk to. We do not sell your personal data. You can ask for your account to be deleted at any time, and that erases your content, your messages and your details.',
      ),
      (
        'What we keep',
        'Your account details (name, username, email, date of birth, country, language), the photos, clips, moments, comments and messages you send, the people you follow and who follows you, what you like, save and repost, and simple counts such as views, reach and watch time.',
      ),
      (
        'Why we keep it',
        'To run the app: to show your content to the audience you choose, to let people find and message you, to show you analytics about your own posts, and to keep the service safe. We do not sell your personal data and we do not share it with advertisers.',
      ),
      (
        'Who can see it',
        'Posts are visible to everyone unless you pick Followers only or Only me, or switch on a private account. Messages are visible to the people in the chat. Analytics are only ever shown to you, and they are totals, never a list of who watched. You can block anyone in Settings.',
      ),
      (
        'Where it is stored',
        'Your account and your messages live in Google Firebase (Firebase Authentication and Cloud Firestore). Photos, clips, voice files and sounds you add from your phone live in our own media storage. Songs offered inside the app are 30 second previews from Apple (iTunes); free music comes from the Jamendo catalogue, found through Openverse.',
      ),
      (
        'On your phone',
        'The app saves your language, accessibility choices, watch history and screen time on your phone only. It asks your permission before it uses the camera, the microphone, your photos or your location, and you can take it back in Android settings.',
      ),
      (
        'Deleting your account',
        'Settings > Account > Delete account. The app opens an email to techlabs.hyper@gmail.com that is already filled in with your username and account id; send it and we delete the account within 7 days and reply to say it is done. That erases your profile and details, your posts, clips, moments and stories, your comments and replies, your likes, saves and reposts, your chats and messages, your followers and following lists, your blocks and your notifications. The photos, clips and sound files you uploaded are removed from storage, and the sign-in itself is removed from Firebase Authentication, so the email and password stop working. It cannot be undone. A short record of reports and blocks may be kept for up to 30 days to keep the service safe, and nothing else is kept. Nothing is deleted while you wait, so you can keep using the app until we reply.',
      ),
      (
        'Children',
        'You must be at least 13 years old to make an account. That is why we ask for your date of birth. If a child\'s account is reported to us, we remove it and its content.',
      ),
      (
        'Your choices',
        'You can edit or delete any post at any time, clear your watch history and screen time, make your account private, block people, and ask for a copy of what we hold by writing to techlabs.hyper@gmail.com.',
      ),
      (
        'Changes',
        'If this policy changes, the new version is published on this page with a new date. Keeping the app installed means you accept it.',
      ),
      (
        'Contact',
        'Questions, or anything about your data: techlabs.hyper@gmail.com.',
      ),
];

const List<(String, String)> kTermsSections = [
      (
        'Using the app',
        'You must be at least 13 years old. You are responsible for your account and for what you post. Keep your password to yourself and do not let anyone else use your account.',
      ),
      (
        'Your content',
        'You keep the rights to what you post. By posting you allow InstantGram to store it and show it to the audience you choose, and to remove it when it breaks these terms. Only post what you have the right to share.',
      ),
      (
        'Not allowed',
        'Hate, harassment, threats, nudity or sexual content involving minors, scams, spam, violence, and anything that breaks the law or other people\'s rights. Impersonating someone, and automated posting, are not allowed either.',
      ),
      (
        'Audio',
        'You can import your own audio from your phone: add only audio you have the right to use, and it is uploaded with your post and removed with it. Songs offered inside the app are 30 second previews that Apple publishes to promote its music; they belong to their owners, are used only inside the app, and the artist\'s name is always shown. Free music is shared by its artists under Creative Commons licences (the Jamendo catalogue, found through Openverse) and is credited in the app. Do not copy, download or resell any of it outside InstantGram.',
      ),
      (
        'Deleting your account',
        'You can ask for your account to be deleted in the app: Settings > Account > Delete account opens an email to techlabs.hyper@gmail.com that is already filled in with your username and account id. We remove the account within 7 days and reply when it is done. Everything that goes with the account (content, messages and details) is erased, and it cannot be undone. The details are in the Privacy Policy.',
      ),
      (
        'Reports and removal',
        'People can report clips, posts and comments. We may remove content or accounts that break these terms, usually after a look at the report. Repeated or serious cases are removed without warning.',
      ),
      (
        'The app is provided as is',
        'InstantGram is free and provided as is. We do our best to keep it running, but we are not liable for lost content, lost reach or anything else that comes with using a free service. Keep your own copies of anything precious to you.',
      ),
      (
        'Changes',
        'We may update these terms. Using the app after a change means you accept it.',
      ),
      (
        'Contact',
        'Questions or reports: techlabs.hyper@gmail.com.',
      ),
];
