// Default moderation word lists. Same as signer/lib/mod_words.json (test/v1310_test.dart
// checks it). word = whole word, word* = anywhere inside a word, "two words" = phrase.
// The admin panel can add, remove and allow words (Firestore config/moderation).

/// Never allowed in public text (posts, comments, bios, usernames): the post is stopped.
const List<String> kBlockedWords = [
  "nigger*",
  "nigga*",
  "faggot*",
  "fagot",
  "chink",
  "kike",
  "spic",
  "tranny",
  "retard",
  "retarded",
  "rapist",
  "rape",
  "raping",
  "pedo",
  "pedophile",
  "paedophile",
  "childporn",
  "cp porn",
  "kill yourself",
  "kill urself",
  "kys",
  "go die",
  "hang yourself",
  "madarchod*",
  "maderchod*",
  "madarjat*",
  "behenchod*",
  "bhenchod*",
  "behenchodd*",
  "bhanchod*",
  "bhosdike*",
  "bhosadike*",
  "bhosdiwal*",
  "bhosda*",
  "bhosri*",
  "randi*",
  "randwa",
  "chinal",
  "मादरचोद",
  "बहनचोद",
  "भोसड़ीके",
  "भोसडीके",
  "रंडी",
  "छिनाल",
];

/// Swear words: hidden with stars (f***) in public text.
const List<String> kMildWords = [
  "fuck*",
  "fuk",
  "fuq",
  "fck",
  "fcking",
  "fking",
  "wtf",
  "stfu",
  "shit",
  "shitty",
  "bullshit",
  "shithead",
  "bitch*",
  "asshole*",
  "ass",
  "arsehole",
  "bastard",
  "dick",
  "dickhead",
  "pussy",
  "cunt",
  "whore",
  "slut",
  "motherfucker",
  "porn",
  "boobs",
  "cock",
  "wanker",
  "twat",
  "douche",
  "jerkoff",
  "chutiya*",
  "chutiye",
  "chutia",
  "choot",
  "chut",
  "bsdk",
  "bkl",
  "gandu",
  "gaandu",
  "gaand",
  "gand",
  "harami",
  "haramkhor",
  "kamina",
  "kamine",
  "kutta",
  "kutte",
  "kutiya",
  "lund",
  "lauda",
  "lavda",
  "lawda",
  "lodu",
  "jhaat",
  "jhatu",
  "tatte",
  "chodu",
  "chod",
  "chodna",
  "चूतिया",
  "चुतिया",
  "गांडू",
  "गाँड",
  "हरामी",
  "कमीना",
  "कुत्ता",
  "कुतिया",
  "लौड़ा",
  "लंड",
  "चोद",
];
